package org.gk.shopping.app.bean;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PhoneNumbers generated by hbm2java
 */
@Entity
@Table(name = "phone_numbers", catalog = "gkapp", uniqueConstraints = @UniqueConstraint(columnNames = "phone_number"))
public class PhoneNumbers implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4543401834574654304L;
	private Integer id;
	private Users users;
	private String title;
	private String phoneNumber;
	private String stdCode;
	private String countryCode;

	public PhoneNumbers() {
	}

	public PhoneNumbers(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	public PhoneNumbers(Users users, String title, String phoneNumber, String stdCode, String countryCode) {
		this.users = users;
		this.title = title;
		this.phoneNumber = phoneNumber;
		this.stdCode = stdCode;
		this.countryCode = countryCode;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user")
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "title", length = 45)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "phone_number", unique = true, nullable = false, length = 15)
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Column(name = "std_code", length = 5)
	public String getStdCode() {
		return this.stdCode;
	}

	public void setStdCode(String stdCode) {
		this.stdCode = stdCode;
	}

	@Column(name = "country_code", length = 5)
	public String getCountryCode() {
		return this.countryCode;
	}

	public void setCountryCode(String countryCode) {
		this.countryCode = countryCode;
	}

}
